name: ci

on:
  push:
jobs:
  deploy_ui_kit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: info
        id: info
        shell: bash
        run: |
          echo "##[set-output name=node_version;]$(cat .nvmrc)"

      - id: use_node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.info.outputs.node_version }}

      - name: ci_cache
        id: ci_cache
        uses: actions/cache@v1
        with:
          key: ci_cache-${{ hashFiles('**/yarn.lock') }}
          path: node_modules
          restore-keys: |
            ci_cache-${{ hashFiles('**/yarn.lock') }}
            ci_cache-

      - name: install
        id: install
        run: |
          mkdir -p ci_cache/global_yarn_cache
          yarn install --frozen-lockfile --cache-folder ci_cache/global_yarn_cache

      - id: test
        name: test
        run: |
          yarn test

      - id: publish
        name: publish
        uses: primer/publish@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          args: "-- --unsafe-perm"
