name: ci

on:
  push:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: info
        id: info
        shell: bash
        run: |
          echo "##[set-output name=node_version;]$(cat .nvmrc)"
          echo "##[set-output name=yarn_cache;]$(yarn cache dir)"

      - id: use_node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.info.outputs.node_version }}

      - name: ci_cache
        id: ci_cache
        uses: actions/cache@v1
        with:
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          path: ${{ steps.info.outputs.yarn_cache }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install
        id: install
        run: |
          yarn install --frozen-lockfile

      - id: test
        name: test
        run: |
          yarn test

      - id: build
        name: build
        run: |
          yarn build

      - id: release
        name: release
        run: |
          yarn release -- --prerelease
